In [8]:
import numpy as np
import pandas as pd
from scipy.optimize import linprog

df = pd.DataFrame(
    [
        [20, 5, 35, 75],
        [15, 2, 20, 55],
        [3, 14, 17, 60],
        [80, 50, 60, None],
    ],
    columns=['지역1', '지역2', '지역3', '총 생산량'],
    index=['공장A', '공장B', '공장C', '총 수요량'],
)
df

지역1  지역2  지역3  총 생산량
공장A     20    5   35   75.0
공장B     15    2   20   55.0
공장C      3   14   17   60.0
총 수요량   80   50   60    NaN

In [9]:
# 비용 행렬
cost = [
    [20, 5, 35],
    [15, 2, 20],
    [3, 14, 17],
]
# 목적함수 계수 : 비용 행렬을 1차원으로 변환
cost = np.array(cost).flatten()

In [10]:
supply = [75, 55, 60]  # 각 공장별 생산량

A_supply = [
    [1, 1, 1, 0, 0, 0, 0, 0, 0],  # 공장A
    [0, 0, 0, 1, 1, 1, 0, 0, 0],  # 공장B
    [0, 0, 0, 0, 0, 0, 1, 1, 1],  # 공장C
]

In [11]:
demand = [80, 50, 60]  # 각 지역별 수요량

A_demand = [
    [1, 0, 0, 1, 0, 0, 1, 0, 0],  # 지역1
    [0, 1, 0, 0, 1, 0, 0, 1, 0],  # 지역2
    [0, 0, 1, 0, 0, 1, 0, 0, 1],  # 지역3
]

In [12]:
A_eq = np.array(A_supply + A_demand)
b_eq = np.array(supply + demand)

bounds = [(0, None)] * len(cost)

In [17]:
reg = linprog(
    c=cost,
    A_eq=A_eq,
    b_eq=b_eq,
    bounds=bounds,
    method='highs',
)
print(reg.x.reshape(3, 3))
print(reg.fun)

[[25. 50.  0.]
 [ 0.  0. 55.]
 [55.  0.  5.]]
2100.0
